ll# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  py310:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install nose2[coverage_plugin]
        pip install -e .[ps,signalfd]
    - name: Test with nose2
      run: |
        nose2 --coverage-report=xml --with-coverage --plugin nose2.plugins.junitxml --junit-xml -v -s tests
    - name: JUnit version fix
      run: |
        { echo '<?xml version="1.0" encoding="UTF-8"?>'; echo '<testsuites time="15.682687">'; cat pieshell/nose2-junit.xml; echo '</testsuites>'; } > x
        mv x pieshell/nose2-junit.xml
        echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        cat pieshell/nose2-junit.xml
        echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - name: Generate badges
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ae708112848f5b5d4bd17e156a2f53e3
        token: ${{ secrets.GIST_TOKEN }}
